import http from 'k6/http';
import { check, sleep } from 'k6';

export let options = {
  vus: 5, 
  duration: '20s',
};

export default function () {
  const url = 'https://jsonplaceholder.typicode.com/posts';
  const payload = JSON.stringify({
    title: 'Test Post',
    body: 'This is a test post generated by k6.',
    userId: 1,
  });

  const params = {
    headers: {
      'Content-Type': 'application/json',
    },
  };

  const res = http.post(url, payload, params);

  check(res, {
    'status is 201': (r) => r.status === 201,
    'response contains id': (r) => JSON.parse(r.body).hasOwnProperty('id'),
  });

  sleep(1);
}
